"""добавили признак публикации

Revision ID: d9ed0b8d19d0
Revises: 26ed8b6a91d0
Create Date: 2021-03-16 17:24:57.957347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ed0b8d19d0'
down_revision = '26ed8b6a91d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
