"""добавили признак публикации

Revision ID: eb88834f1cf1
Revises: d9ed0b8d19d0
Create Date: 2021-03-16 18:44:31.485141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb88834f1cf1'
down_revision = 'd9ed0b8d19d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('work_size', sa.Integer(), nullable=True),
    sa.Column('collaborators', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('team_leader', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_leader'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
